export const FATURAMENTO = {
    TXT_INF_FAT: '#checkout_one > div > div > div:nth-child(1) > div > div:nth-child(2) > h3 > font > font',
    TXT_NAME: '<font style="vertical-align: inherit;">Primeiro nome </font>',
    INPUT_NAME: '#fname',
    INPUT_LAST_NAME: '#lname',
    INPUT_COMPANY: '#cname',
    INPUT_EMAIL: '#email',
    INPUT_COUNTRY: '#country',
    INPUT_STATE: '#city',
    INPUT_ZIP: '#zip',
    INPUT_ADDRESS: '#faddress',
    INPUT_NOTES: '#messages',
    CHECK_SAVE: '#materialUnchecked',
    BTN_SAVE: '#checkout_one > div > div > div:nth-child(1) > div > button',
    RADIO_PAYMENT: '#css',
    BTN_PG: '#checkout_one > div > div > div:nth-child(2) > div:nth-child(2) > button',
    ALERT_SUCCESS:'.offer_modal_left',
    TXT_PAYMENT: '.check-heading',
    TXT_INF_REGISTRED:'#checkout_one',
}